version: '2'
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  cassandra:
    container_name: cassandra
    image: cassandra
    ports:
      - "9042:9042"


